# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestCase1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testCase1(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(2)").send_keys("an@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(3)").send_keys("an")
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(1)").send_keys("ansh")
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(3)").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(4)").send_keys("19")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(1)").send_keys("an@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(2)").send_keys("an")
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-field:nth-child(2)").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
    self.driver.find_element(By.LINK_TEXT, "Upload").click()
    self.driver.find_element(By.LINK_TEXT, "Upload Image").click()
    self.driver.find_element(By.LINK_TEXT, "Upload").click()
    self.driver.find_element(By.LINK_TEXT, "Upload pdf").click()
    self.driver.find_element(By.LINK_TEXT, "Upload").click()
  
test=TestTestCase1()
test.setup_method()
test.test_testCase1()
test.teardown_method()